language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
# command to install dependencies
install:
  - pip install -e .
# command to run tests
script:
  - python -c "from ikarus import classifier, utils, data"
